name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build and lint
      run: cargo clippy -- -D warnings
    - name: test
      run: cargo test
    - name: test-bpf
      run: cargo test-bpf -- --show-output

defaults:
  run:
    working-directory: program